version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 8080:80
  
     volumes:
         - ./php_code/:/var/www/html/

   php:
     build: ./php/
     expose:
       - 9000
     volumes:
        - ./php_code/:/var/www/html/

   mysql:
     image: mysql:latest
     container_name: mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
     ports:
       - 3306:3306
     volumes:
       - ./mysql_data:/var/lib/mysql
